services:
    php:
        build:
            context: ./docker/php
        container_name: export-thing-php
        volumes:
            - .:/var/www/export-thing
        depends_on:
            - db

    nginx:
        image: nginx:alpine
        container_name: export-thing-nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/export-thing
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    db:
        image: postgres:16
        container_name: export-thing-db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
